authentication/urls.py
from django.urls import include, path
from .template_views import accept_follow_request, deny_follow_request, home, signin, signout, signup, create_post, profilepage, update_profile, like_post, post_detail, delete_post, add_comment, delete_comment, user_search, follow, edit_post, all_users, like_comment, notifications_view, mark_all_notifications_as_read, get_unread_notifications_count
from authentication.template_views import notifications_view
from authentication.api_views import RegisterView
from authentication.api_views import ProfileViewSet

urlpatterns = [
    path('api/', include('authentication.api')),
    # path('', home, name='home'),
    # path('signin/', signin, name='signin'),
    # path('signout/', signout, name='logout'),
    # path('signup/', signup, name='signup'),
    # path('create_post/', create_post, name='create_post'),
    # path('p/<str:username>/', profilepage, name='profile'),
    # path('update_profile/', update_profile, name='update_profile'),
    # path('like_post/<int:post_id>/', like_post, name='like_post'),
    # path('post/<int:post_id>/', post_detail, name='post_detail'),
    # path('post/<int:post_id>/delete/', delete_post, name='delete_post'),
    # path('add_comment/<int:post_id>/', add_comment, name='add_comment'),
    path('', home, name='home'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='logout'),
    path('signup/', signup, name='signup'),
    path('create_post/', create_post, name='create_post'),
    path('p/<str:username>/', profilepage, name='profile'),
    path('update_profile/', update_profile, name='update_profile'),
    path('like_post/<int:post_id>/', like_post, name='like_post'),
    path('post/<int:post_id>/', post_detail, name='post_detail'),
    path('post/<int:post_id>/delete/', delete_post, name='delete_post'),
    path('add_comment/<int:post_id>/', add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/',
         delete_comment, name='delete_comment'),
    path('search/', user_search, name='user_search'),  # testing search
    path('follow/', follow, name='follow'),
    path('edit_post/<int:post_id>/', edit_post, name='edit_post'),
    path('authors/', all_users, name='all_users'),
    path('notifications/', notifications_view, name='notifications'),
    path('like_comment/<int:comment_id>/', like_comment, name='like_comment'),
    path('notifications/', notifications_view, name='notifications'),
    path('notifications/mark-all-as-read/', mark_all_notifications_as_read,
         name='mark-all-notifications-as-read'),
    path('notifications/unread-count/', get_unread_notifications_count,
         name='unread-notifications-count'),

    path('accept-follow-request/<int:notification_id>/',
         accept_follow_request, name='accept_follow_request'),
    path('deny-follow-request/<int:notification_id>/',
         deny_follow_request, name='deny_follow_request'),

    path('profile/<str:username>/', ProfileViewSet.as_view(
        {'get': 'retrieve', 'put': 'update'}), name='profile-detail'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from authentication.api_views import RegisterView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="cuz SocialDistribution OpenAPI",
        default_version='v1',
        description="API documentation for CMPUT 404 Social Distribution",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('api/register/', RegisterView.as_view(), name='api_register'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

authentication/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
import requests
from datetime import datetime
from django import forms
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver


class Node(models.Model):
    name = models.CharField(max_length=100, unique=True)
    host_url = models.URLField(unique=True)
    is_active = models.BooleanField(
        default=True, help_text="Status to enable/disable node interaction")
    username = models.CharField(
        max_length=100, null=True, blank=True, help_text="Username for the node")
    password = models.CharField(
        max_length=100, null=True, blank=True, help_text="Password for the node")

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Set default to empty string
    displayName = models.CharField(max_length=100, blank=True, default='')
    # Set default to empty string
    bio = models.TextField(blank=True, default='')
    # Set default to empty string
    github = models.URLField(blank=True, default='')
    # Set default to empty string
    profileImage = models.URLField(blank=True, default='')
    following = models.ManyToManyField(
        'self', symmetrical=False, related_name='followers', blank=True)
    liked = models.ManyToManyField(
        'Post', related_name='liked_posts', blank=True)
    posts = models.ManyToManyField('Post', related_name='posts', blank=True)

    class Meta:
        ordering = ['id']

    def get_absolute_url(self):
        return reverse('profile-detail', args=[str(self.id)])

    def __str__(self):
        return self.user.username  # TESTING

    def get_friends(self):
        # Users that the current user follows and also follow the current user back
        users_i_follow = self.following.all()
        # Users that follow the current user back
        friends = users_i_follow.filter(following__id=self.id)

        return friends

    def get_github_activity(self):
        # Check if the GitHub URL is None
        if self.github is None:
            # If it is, return an error message or an empty list
            return {'error': 'No GitHub URL'}
        # Extract the username from the GitHub URL
        github_username = self.github.split('/')[-1]

        # Make a request to the GitHub API
        response = requests.get(
            f'https://api.github.com/users/{github_username}/events')

        # Check if the request was successful
        if response.status_code == 200:
            # Get the JSON data from the response
            events = response.json()

            # Reverse the list of events
            events.reverse()
            return events
        else:
            # If the request was not successful, return an error message
            return {'error': 'Could not get GitHub activity'}

    def create_posts_from_github_activity(self):
        # Get the GitHub activity
        github_activity = self.get_github_activity()

        # Check if there was an error
        if 'error' in github_activity:
            return github_activity
        # Loop through the GitHub activity
        for event in github_activity:
            # Create a new Post instance for each event
            if self.posts.filter(github_id=event['id']).exists() == False:
                created_at = datetime.strptime(
                    event['created_at'], "%Y-%m-%dT%H:%M:%SZ")
                formatted_date = created_at.strftime("%B %d, %Y")
                post = Post.objects.create(
                    user=self.user,
                    profile=self,
                    github_id=event['id'],
                    content=f"Github Event - {event['type']} in {event['repo']['name']} on {formatted_date}",
                )
                self.posts.add(post)

        # Save the user's profile
        self.save()

    def get_absolute_url(self):
        return reverse('profile', kwargs={'username': self.user.username})

    def __str__(self):
        return self.user.username


class Post(models.Model):

    VISIBILITY_CHOICES = [('public', 'Public'),
                          ('private', 'Private'), ('unlisted', 'Unlisted')]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # add profile as well and give it a default value
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    content = models.TextField()
    # image = models.ImageField(upload_to='posts',  blank=True)
    image = models.URLField(blank=True, null=True)
    liked = models.ManyToManyField(
        Profile, related_name='liked_by', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    github_id = models.CharField(max_length=100, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(
        User, related_name='liked_posts', blank=True)
    visibility = models.CharField(
        max_length=10, choices=VISIBILITY_CHOICES, default='public')
    cm_toggle = models.BooleanField(default=False)  # CommonMark toggle
    content_markdown = models.TextField()
    image_type = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.content[:20]

    def num_likes(self):
        return self.liked.all().count()

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])

    class Meta:
        ordering = ('-created',)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(
        User, related_name='liked_comments', blank=True)
    cm_toggle_comment = models.BooleanField(
        default=False)  # CommonMark toggle for comments

    def __str__(self):
        return self.content[:20]

    def get_absolute_url(self):
        return reverse('comment-detail', args=[str(self.post.profile.id), str(self.post.id), str(self.id)])

    class Meta:
        ordering = ('-created',)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image', 'cm_toggle',]  # Added 'is_unlisted'


class Notification(models.Model):
    TYPE_CHOICES = (
        ('like', 'Like'),
        ('comment', 'Comment'),
        ('follow', 'Follow Request'),
        ('accepted_follow', 'Accepted Follow Request'),
        ('github_activity', 'GitHub Activity'),
        ('post', 'New Post'),
    )
    recipient = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='notifications')
    sender = models.ForeignKey(User, on_delete=models.CASCADE,
                               null=True, blank=True, related_name='sent_notifications')
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, null=True, blank=True)
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.recipient.username} - {self.get_type_display()}"

    def notification_text(self):
        """
        Generates a custom notification text based on the notification type.
        This method can be extended to include more personalized text for each notification.
        """
        if self.type == 'like':
            return f"{self.sender.username} liked your post."
        elif self.type == 'comment':
            return f"{self.sender.username} commented on your post: '{self.post.content[:30]}...'"
        elif self.type == 'follow':
            return f"{self.sender.username} has started following you."
        elif self.type == 'github_activity':
            return "New activity on your GitHub!"
        elif self.type == 'post':
            return f"{self.sender.username} created a new post."
        else:
            return "You have a new notification."


class FollowRequest(models.Model):
    sender = models.ForeignKey(
        User, related_name='sent_follow_requests', on_delete=models.CASCADE)
    receiver = models.ForeignKey(
        User, related_name='received_follow_requests', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('sender', 'receiver')

    def __str__(self):
        return f"From {self.sender.username} to {self.receiver.username}"

authentication/templates/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Post</title>
    <style>
        .form-container {
            border: 10px solid black; /* Adjusted for proper CSS */
            padding: 10px;
            margin: 10px;
        }
        .form-content {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
        }
        textarea, input, button {
            margin: 10px;
            padding: 10px;
        }
        input, button {
            padding: 5px; /* Adjusted for better appearance */
        }
    </style>
</head>
<body>
    <div class="form-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-content">
                <textarea name="content" placeholder="change your mind here :3">{{ post.content_markdown }}</textarea>
                <input type="file" name="image">
                <input type="checkbox" name="cm_toggle" {% if post.cm_toggle %}checked{% endif %}> Use CommonMark
                <button type="submit">Save changes</button>
            </div>
        </form>
    </div>
</body>
</html>

authentication/templates/index.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Authentication</title>
    <meta name="description" content="" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale= -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>
  <body>
    {% if user.is_authenticated %}
    <div style="display: flex; justify-content: space-between; align-items: center;">
      <h1>Welcome {{ user.username }}</h1>
      <h4>{{ user.email }}</h4>

      {% if user.is_authenticated and user_profile %}
        <h4>Followers : {{followers}}</h4>
        <h4>Following : {{following}}</h4>

        <a href="{% url 'profile' user.username %}">
          <img 
              height="100"
              style="border-radius: 50%;"
              width="100"
              src="{{ user_profile.profileImage }}" alt="Profile Picture">
      </a>
      {% endif %}
      <div>
        <button type="submit"><a href="/signout"> Sign Out</a></button>
      </div>
    </div>

    <div style="border: 10px; border-color: black; border-style: solid; padding: 10px; margin: 10px;">
      <form method="post" enctype="multipart/form-data" action="{% url 'create_post' %}">
        {% csrf_token %}
        <div style="display: flex; flex-direction: column; justify-content: space-between; align-items: center;">
          <select name="visibility">
            <option value="public">Public</option>
            <option value="private">Private</option>
            <option value="unlisted">Unlisted</option>
          </select>
          <textarea name="content" placeholder="What's on your mind?" style="margin: 10px; padding: 10px;"></textarea>
          <input type="file" name="image" style="margin: 10px;">
          <input type="checkbox" name="cm_toggle"> Use CommonMark
          <button type="submit" style="margin: 10px;">Post</button>
        </div>
      </form>
    </div>


    <form method="get" action="{% url 'user_search' %}">
      <input type="text" name="q" placeholder="Search users...">
      <button type="submit">Search</button>
      <a href="{% url 'all_users' %}"><button type="button">All Users</button></a>
    </form>

    <h2>Posts - {{posts_length}}</h2>
    {% for post in posts %}
      {% if post.visibility == 'public' or post.user.profile.id in friend_ids or request.user.id == post.user.profile.id %}
        <div style="border: 10px; border-color: black; border-style: solid; padding: 10px; margin: 10px;">
          <div style="display: flex; flex-direction: column; justify-content: space-between; align-items: center;">
            <div>Content : {{ post.content|safe }}</div>
            {% if post.image %}  <!-- if there is an image display it -->
              <h3>Image : <img height="100" width="100" src="data:{{ post.image_type }};base64,{{ post.image }}" alt="Post Image"/> </h3>
            {% endif %}
            <h3>By : {{post.profile.displayname}} (/{{post.user.username}})</h3>
            <h3>Created At : {{post.created}}</h3>
            <a href="{% url 'profile' post.user.username %}">
              <img height="40" width="40" style="border-radius: 50%;"
                  src="{{post.profile.pfp}}" alt="Profile Picture"/>
            </a>
            <!-- <h3>Like : {{post.liked}}</h3> -->
            <a href="{% url 'like_post' post.id %}" class="like-button" data-post-id="{{ post.id }}">
              {% if request.user in post.likes.all %}
                <i class="fas fa-heart"></i> <!-- filled heart icon -->
              {% else %}
                <i class="far fa-heart"></i> <!-- empty heart icon -->

              {% endif %}
            <h3>By : {{post.profile.displayname}} (/{{post.user.username}})</h3>
            <h3>Created At : {{post.created}}</h3>
            <a href="{% url 'profile' post.user.username %}">
              <img height="40" width="40" style="border-radius: 50%;"
                  src="{{post.profile.profileImage}}" alt="Profile Picture"/>
            </a>
            <!-- <h3>Like : {{post.liked}}</h3> -->
            <a href="{% url 'like_post' post.id %}" class="like-button" data-post-id="{{ post.id }}">
              {% if request.user in post.likes.all %}
                <i class="fas fa-heart"></i> <!-- filled heart icon -->
              {% else %}
                <i class="far fa-heart"></i> <!-- empty heart icon -->
              {% endif %}
              <h3>By : {{post.profile.displayname}} (/{{post.user.username}})</h3>
              <h3>Created At : {{post.created}}</h3>
              <a href="{% url 'profile' post.user.username %}">
                <img height="40" width="40" style="border-radius: 50%;"
                    src="{{post.profile.pfp}}" alt="Profile Picture"/>
              </a>
              <!-- <h3>Like : {{post.liked}}</h3> -->
              <a href="{% url 'like_post' post.id %}" class="like-button" data-post-id="{{ post.id }}">
                {% if request.user in post.likes.all %}
                  <i class="fas fa-heart"></i> <!-- filled heart icon -->
                {% else %}
                  <i class="far fa-heart"></i> <!-- empty heart icon -->
                {% endif %}
              </a>
              <span id="like-count-{{ post.id }}">{{ post.likes.count }}</span> <!-- like count -->
              <a href="{% url 'post_detail' post.id %}">Comments ({{ post.comment_set.count }})</a>
              {% if user.id == post.user.id %}  <!-- if the current user is the author of the post -->
                <a href="{% url 'delete_post' post.id %}">Delete</a>
                <a href="{% url 'edit_post' post.id %}">Edit</a>
              {% endif %}
            </div>
          </div>
      {% endif %}
    {% endfor %}


    {% else %}
    <h3>Welcome to main page</h3>
    <button type="submit"><a href="/signup"> SignUp</a></button>
    <button type="submit"><a href="/signin"> SignIn</a></button>
    {% endif %} 

    {% for message in messages %}
    <h5>Message : {{message}}</h5>
    {% endfor %}
    <script src="" async defer></script>
  </body>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
  $(document).ready(function() {
    $('.like-button').click(function(event) {
        event.preventDefault();
        var post_id = $(this).data('post-id');
        var url = "{% url 'like_post' '123' %}".replace('123', post_id);
        var icon = $(this).find('i');
        $.ajax({
            url: url,
            dataType: 'json',
            success: function(data) {
                $('#like-count-' + post_id).text(data.like_count);
                if (data.user_likes) {
                    icon.removeClass('far').addClass('fas');
                } else {
                    icon.removeClass('fas').addClass('far');
                }
            }
        });
    });
});
  </script>

</html>

authentication/templates/post_detail.html
{% load static %}
{% load static my_filters %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<style>
    .emoji-in-post {
        width: 35px;
        height: 35px;
    }
</style>
<div>
    {% if post.cm_toggle %}
        <!-- Apply the emoji conversion filter if Markdown is enabled for the post -->
        {% autoescape off %}
            {{ post.content|safe|replace_from_dict:cm_emojis }}
        {% endautoescape %}
    {% else %}
        <!-- Just render the post content safely if Markdown isn't enabled -->
        {{ post.content|safe }}
    {% endif %}
</div>
<p>Posted by {{ post.user.username }} on {{ post.created }}</p>
<p>Type: {{ post.get_visibility_display }}</p> <!-- Display post visibility -->
{% if post.image %}
    <img src="{{ post.image }}" alt="Post Image" style="width: auto; height: 200px;">
{% endif %}
<!-- Like button -->
<a href="{% url 'like_post' post.id %}" class="like-button" data-post-id="{{ post.id }}">
  {% if request.user in post.likes.all %}
    <i class="fas fa-heart"></i> <!-- filled heart icon -->
  {% else %}
    <i class="far fa-heart"></i> <!-- empty heart icon -->
  {% endif %}
</a>
<span id="like-count-{{ post.id }}">{{ post.likes.count }}</span> <!-- like count -->

<!-- Display other post details here -->

<h2>Comments</h2>
<form method="post" action="{% url 'add_comment' post.id %}">
    {% csrf_token %}
    <textarea name="content"></textarea>
    <input type="checkbox" name="cm_toggle_comment"> Use CommonMark 
    <div id="emoji-picker-comment" style="display: none;">
    <img src="{% static 'cm-emojis/angry.png' %}" alt=":angry: " title="angry" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/bicycle.png' %}" alt=":bicycle: " title="bicycle" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/chef.png' %}" alt=":chef: " title="chef" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/deaf.png' %}" alt=":deaf: " title="deaf" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/depression.png' %}" alt=":depression: " title="depression" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/devious.png' %}" alt=":devious: " title="devious" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/disgust.png' %}" alt=":disgust: " title="disgust" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/fight.png' %}" alt=":fight: " title="fight" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/funny.png' %}" alt=":funny: " title="funny" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/goodbye.png' %}" alt=":goodbye: " title="goodbye" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/jojothinking.png' %}" alt=":jojothinking: " title="jojothinking" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/looking.png' %}" alt=":looking: " title="looking" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/love.png' %}" alt=":love: " title="love" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/mischievous.png' %}" alt=":mischievous: " title="mischievous" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/nerd.png' %}" alt=":nerd: " title="nerd" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/pet.gif' %}" alt=":pet: " title="pet" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/pray.png' %}" alt=":pray: " title="pray" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/sad.png' %}" alt=":sad: " title="sad" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/shrug.png' %}" alt=":shrug: " title="shrug" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/stare.png' %}" alt=":stare: " title="stare" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/sunglasses.gif' %}" alt=":sunglasses: " title="sunglasses" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/swag.png' %}" alt=":swag: " title="swag" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/waiting.png' %}" alt=":waiting: " title="waiting" class="emoji emoji-in-post">
    <img src="{% static 'cm-emojis/walk.gif' %}" alt=":walk: " title="walk" class="emoji emoji-in-post">
</div>
    <button type="submit">Add Comment</button>
</form>

{% for comment in comments %}
    <div>
        <h3>{{ comment.user.username }} commented on {{ comment.created }}</h3>
        <p>
            {% if comment.cm_toggle_comment %}
                {% autoescape off %}
                    {{ comment.content|safe|replace_from_dict:cm_emojis }}
                {% endautoescape %}
            {% else %}
                {{ comment.content|safe }}
            {% endif %}
        </p>
        <!-- Like button for the comment -->
        <a href="javascript:void(0);" class="like-comment-button" data-comment-id="{{ comment.id }}">
          {% if request.user in comment.likes.all %}
            <i class="fas fa-heart"></i>
          {% else %}
            <i class="far fa-heart"></i>
          {% endif %}
        </a>
        <span id="like-comment-count-{{ comment.id }}">{{ comment.likes.count }}</span>
        {% if request.user == comment.user %}
            <form method="post" action="{% url 'delete_comment' comment.id %}">
                {% csrf_token %}
                <button type="submit">Delete Comment</button>
            </form>
        {% endif %}
    </div>
{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
  $('.like-button').click(function(event) {
      event.preventDefault();
      var post_id = $(this).data('post-id');
      var url = "{% url 'like_post' '123' %}".replace('123', post_id);
      var icon = $(this).find('i');
      $.ajax({
          url: url,
          dataType: 'json',
          success: function(data) {
              $('#like-count-' + post_id).text(data.like_count);
              if (data.user_likes) {
                  icon.removeClass('far').addClass('fas');
              } else {
                  icon.removeClass('fas').addClass('far');
              }
          }
      });
  });
});

$(document).ready(function() {
  $('.like-comment-button').click(function(event) {
      event.preventDefault();
      var commentId = $(this).data('comment-id');
      var url = "{% url 'like_comment' '123' %}".replace('123', commentId); // Update this URL
      var icon = $(this).find('i');
      $.ajax({
          url: url,
          method: 'POST', // Ensure you use POST method
          data: {
              'csrfmiddlewaretoken': '{{ csrf_token }}', // Pass the CSRF token
              'comment_id': commentId,
          },
          success: function(response) {
              // Update the like count and icon based on response
              $('#like-comment-count-' + commentId).text(response.likes_count);
              if (response.liked) {
                  icon.removeClass('far').addClass('fas');
              } else {
                  icon.removeClass('fas').addClass('far');
              }
          }
      });
  });
});

document.querySelector('input[name="cm_toggle_comment"]').addEventListener('change', function() {
    document.getElementById('emoji-picker-comment').style.display = this.checked ? 'block' : 'none';
});

document.querySelectorAll('#emoji-picker-comment .emoji').forEach(function(emoji) {
    emoji.addEventListener('click', function() {
        document.querySelector('textarea[name="content"]').value += this.alt;
    });
});


</script>

authentication/templates/signup.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Authentication</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=
    <link rel="stylesheet" href="" />
  </head>
  <body>
    <form
      method="post"
      action="/signup/"
      style="
        display: flex;
        flex-direction: column;
        max-width: 300px;
        margin: 0 auto;
      "
      autocomplete="off"
    >
      {% csrf_token %}
      <label for="id_name">Display Name:</label>
      <input id="id_displayName" type="text" name="displayName" maxlength="100" required />

      <label for="id_username">Username:</label>
      <input
        id="id_username"
        type="text"
        name="username"
        maxlength="100"
        required
      />

      <label for="id_password">Password:</label>
      <input id="id_password" type="password" name="password" required />

      <label for="id_email">Email:</label>
      <input id="id_email" type="email" name="email" required />

      <label for="id_email">GitHub URL:</label>
      <input id="id_github" type="url" name="github"/>

      <label for="id_email">Profile Picture URL:</label>
      <input id="id_profileImage" type="url" name="profileImage"/>

      <label for="id_bio">Bio:</label>
      <textarea id="id_bio" name="bio"></textarea>

      <input type="submit" value="Sign Up" />
    </form>
    <script src="" async defer></script>
  </body>
</html>